site_name: Sotig's notes

docs_dir: md
site_dir: docs
plugins:
  - blog
  - search
  - mermaid2
  - glightbox

theme:
  name: material
  palette:
    scheme: slate
    primary: amber
  features:
    - content.code.copy
 
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom