site_name: Sotig's notes

docs_dir: md
site_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: amber
  features:
    - content.code.copy
 
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition